### ISSUE TITLE
Failed to download LolClient.swf from lol_air_client patch 0.0.0.0

### ISSUE THREAD

**Issue by RiotArchiveProject** [LoL-Fantome/LeagueDownloader#2]
I'm sure this is on Riot's side as well.
Got a red square (which I'm guessing implies failed) from the air client's solution for patch 0.0.0.0 on the LolClient.swf

Everything else downloaded as expected

Edit: This isn't a very big deal it's just what I noticed.

**Comment by ChewyBomber** [comment]
It's definitely a compression error coming from Riot. The tool cannot decompress properly the file after downloading it. 
Since it's the first RADS deployment of the air client, I guess their system wasn't perfectly stable at that time. We cannot do anything to fix it though 😃
